---
- name: Install latest docker and docker py
  yum: name={{item}} state=latest
  with_items:
    - docker
    - python-docker-py

- name: Enable Docker registry
  lineinfile:
    dest: /etc/sysconfig/docker
    line: 'ADD_REGISTRY="--add-registry {{ public_registry }}:5000 --add-registry registry.centos.org"'

- name: Reload docker systemd service
  sudo: yes
  systemd: name=docker state=reloaded

- name: Restart Docker
  systemd: name=docker state=restarted enabled=yes

- name: Build container-pipeline image
  sudo: yes
  docker_image:
    state: present
    force: yes
    name: container-pipeline
    path: /opt/cccp-service
  tags:
      - application

- name: Ensure log path exists
  file: path=/srv/pipeline-logs/cccp.log state=touch

- name: Start dispatcher-worker container
  docker_container:
      name: dispatcher-worker
      state: started
      restart: yes
      image: container-pipeline
      command: /opt/cccp-service/container_pipeline/workers/dispatcher.py
      restart_policy: always
      volumes: /srv/pipeline-logs:/srv/pipeline-logs:rw
  tags:
      - application

- name: Start build-worker container
  docker_container:
      name: build-worker
      state: started
      restart: yes
      image: container-pipeline
      command: /opt/cccp-service/container_pipeline/workers/build.py
      restart_policy: always
      volumes: /srv/pipeline-logs:/srv/pipeline-logs:rw
      env:
          JENKINS_MASTER: "{{ groups['jenkins_master'][0] }}"
  tags:
      - application

- name: Start test-worker container
  docker_container:
      name: test-worker
      state: started
      restart: yes
      image: container-pipeline
      command: /opt/cccp-service/container_pipeline/workers/test.py
      restart_policy: always
      volumes: /srv/pipeline-logs:/srv/pipeline-logs:rw
  tags:
      - application

- name: Start delivery-worker container
  docker_container:
      name: delivery-worker
      state: started
      restart: yes
      command: /opt/cccp-service/container_pipeline/workers/delivery.py
      image: container-pipeline
      restart_policy: always
      volumes: /srv/pipeline-logs:/srv/pipeline-logs:rw
  tags:
      - application

- name: Pull Linter image
  docker_image:
      name: registry.centos.org/pipeline-images/dockerfile-lint
      state: present
      force: yes
  tags:
      - application

- name: Copy Dockerfile linter worker
  copy:
      src: ../../scripts/cccp-dockerfile-lint-worker.service
      dest: /etc/systemd/system/cccp-dockerfile-lint-worker.service
  tags:
      - application

- name: Reload Dockerfile linter worker systemd service
  sudo: yes
  systemd: name=cccp-dockerfile-lint-worker state=reloaded
  tags:
      - application

- name: Enable and start Dockerfile linter worker
  systemd: name=cccp-dockerfile-lint-worker enabled=yes state=restarted
  tags:
      - application
