---
- name: Enable epel repo
  yum: name=epel-release state=installed
  when: enable_epel

- name: Install packages on openshift node
  yum: name={{item}} state=installed
  with_items:
    - git
    - beanstalkd

- name: Install latest docker and docker py packages
  yum: name={{ item }} state=latest
  with_items:
      - docker
      - python-docker-py

- name: Reload docker systemd service
  sudo: yes
  systemd: name=docker state=reloaded

- name: Start Docker service
  systemd: name=docker state=started enabled=yes

- name: Start beanstalkd service
  systemd: name=beanstalkd state=started enabled=yes
