---
origin_image_registry: docker.io
origin_image_name: openshift/origin
origin_image_tag: v3.6.0

origin_dir: /var/lib/origin

openshift_volumes_dir: /var/lib/origin/openshift.local.volumes
openshift_etcd_dir: /var/lib/origin/openshift.local.etcd
openshift_config_dir: /var/lib/origin/openshift.local.config

openshift_shared_dirs:
  - /var/lib/origin/openshift.local.volumes
  - /var/lib/origin/openshift.local.config
  - /var/lib/origin/openshift.local.etcd

openshift_volumes:
  - /:/rootfs:ro
  - /var/run:/var/run:rw
  - /sys:/sys:rw
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - /var/lib/docker:/var/lib/docker:rw
  - /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes:rslave
  - /var/lib/origin/openshift.local.config:/var/lib/origin/openshift.local.config:rw
  - /var/lib/origin/openshift.local.etcd:/var/lib/origin/openshift.local.etcd:rw

openshift_dir: /var/lib/origin/openshift.local.config/master
kubeconfig: /var/lib/origin/openshift.local.config/master/admin.kubeconfig

ose_tag: ose-v1.3.0-1

openshift_startup_delay: 75
