---
- name: Install Atomic
  yum: name=atomic state=present
  sudo: yes

- name: Start and Enable docker
  service: name=docker enabled=yes state=started
  sudo: yes

- name: Enable Docker Host socket
  replace: >
    dest=/etc/sysconfig/docker
    regexp="^#?\s*OPTIONS=.*"
    replace='OPTIONS="--selinux-enabled --log-driver=journald -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock"'

- name: Enable Docker Registry
  replace: >
    dest=/etc/sysconfig/docker
    regexp="^#?\s*ADD_REGISTRY=.*"
    replace='ADD_REGISTRY="--add-registry {{ public_registry }} --insecure-registry {{ public_registry }}:5000 "'

- name: Restart Docker
  service: name=docker state=restarted enabled=yes

- name: Wait for Openshift Router to come up
  pause: seconds=50

- name: Run atomic scanner container
  docker_container:
      image: registry.centos.org/pipeline-images/pipeline-scanner:latest
      name: pipeline-scanner
      privileged: true
      volumes:
        - /etc/atomic.d/:/host/etc/atomic.d/
      command: sh /install.sh
      state: started

- name: Ensure /opt/cccp-service/beanstalk_worker dir exists on Jenkins slaves
  file: dest=/opt/cccp-service/beanstalk_worker state=directory

- name: Get scanner worker scripts
  copy:
    src: "{{ item }}"
    dest: /opt/cccp-service/beanstalk_worker
    mode: u+x
  with_items:
    - ../beanstalk_worker/beanstalkc.py
    - ../beanstalk_worker/worker_start_test.py
  when: not vagrant

- name: Get service files for workers
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
      - {src: "../beanstalk_worker/cccp-test-worker.service", dest: /etc/systemd/system/cccp-test-worker.service}

- name: Enable Scanner worker
  service: name="cccp-test-worker" state=restarted enabled=yes

- name: Add host entry for beanstalkd
  shell: echo `ping {{ groups['openshift'][0] }} -c 1 | awk '{print $3}'|head -n 1|sed 's/(//'|sed 's/)//'` openshift >> /etc/hosts

- name: Add host entry for atomic-scan.vm
  shell: echo "127.0.0.1 atomic-scan.vm.centos.org" >> /etc/hosts
