---
- name: Install Atomic
  yum: name=atomic state=present
  sudo: yes

# Fix for issue:  https://github.com/projectatomic/atomic/issues/804
- name: Install python-dateutil
  yum: name=python-dateutil state=present
  sudo: yes

# Patch from https://github.com/projectatomic/atomic/commit/a261270e727353899675a3fde8f9108376bb27cf
- name: Patch atomic scanner to run on non tty input
  replace: >
      dest=/usr/lib/python2.7/site-packages/Atomic/scan.py
      regexp="'-it'"
      replace="'-t'"
  sudo: yes

- name: Install docker
  yum: name=docker state=present
  sudo: yes

- name: Start and Enable docker
  service: name=docker enabled=yes state=started
  sudo: yes

- name: Enable Docker Host socket
  replace: >
    dest=/etc/sysconfig/docker
    regexp="^#*\s*OPTIONS=.*"
    replace='OPTIONS="--selinux-enabled --log-driver=journald -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock"'

- name: Enable Docker Registry
  replace: >
    dest=/etc/sysconfig/docker
    regexp="^#*\s*ADD_REGISTRY=.*"
    replace='ADD_REGISTRY="--add-registry {{ public_registry }} --insecure-registry {{ public_registry }}:5000"'

- name: Set SELinux to permissive
  selinux:
      policy: targeted
      state: permissive

- name: Restart Docker
  service: name=docker state=restarted enabled=yes

- name: Install pipeline-scanner container
  docker_container:
      image: registry.centos.org/pipeline-images/pipeline-scanner:latest
      name: pipeline-scanner
      privileged: true
      volumes:
        - /etc/atomic.d/:/host/etc/atomic.d/
      command: sh /install.sh
      state: started

- name: Install scanner-rpm-verify container
  docker_container:
      image: registry.centos.org/pipeline-images/scanner-rpm-verify:latest
      name: rpm-verify
      privileged: true
      volumes:
        - /etc/atomic.d/:/host/etc/atomic.d/
      command: sh /install.sh
      state: started

- name: Install misc-package-updates container
  docker_container:
      image: registry.centos.org/pipeline-images/misc-package-updates:latest
      name: misc-package-updates
      privileged: true
      volumes:
        - /etc/atomic.d/:/host/etc/atomic.d/
      command: sh /install.sh
      state: started

- name: Ensure /opt/cccp-service/beanstalk_worker dir exists on Jenkins slaves
  file: dest=/opt/cccp-service/beanstalk_worker state=directory

- name: Get scanner worker scripts
  copy:
    src: "{{ item }}"
    dest: /opt/cccp-service/beanstalk_worker
    mode: u+x
  with_items:
    - ../beanstalk_worker/beanstalkc.py
    - ../beanstalk_worker/config.py
    - ../beanstalk_worker/worker_start_scan.py
    - ../beanstalk_worker/constants.py
    - ../beanstalk_worker/scanner.py
  when: not vagrant

- name: Get service files for workers
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
      - {src: "../beanstalk_worker/cccp-scan-worker.service", dest: /etc/systemd/system/cccp-scan-worker.service}

- name: Ensure log path exists
  file: path=/srv/pipeline-logs/cccp.log state=touch

- name: Enable Scanner worker
  service: name="cccp-scan-worker" state=restarted enabled=yes

- name: Replace Beanstalk server with its FQDN for test worker
  replace: >
      dest=/opt/cccp-service/beanstalk_worker/worker_start_scan.py
      regexp="BEANSTALK_SERVER"
      replace='{{ groups['openshift'][0] }}'

- name: Enable Scanner worker
  service: name="cccp-scan-worker" state=restarted enabled=yes
